# Generated by Django 2.2.16 on 2020-11-12 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organzation', '0004_auto_20201106_2106'),
        ('course', '0006_video_learn_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organzation.Teacher', verbose_name='讲师'),
        ),
    ]
