# Generated by Django 2.2.16 on 2020-11-16 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_course_is_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCourse',
            fields=[
            ],
            options={
                'verbose_name': '轮播课程',
                'verbose_name_plural': '轮播课程',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('course.course',),
        ),
    ]
