# Generated by Django 2.2.16 on 2020-11-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organzation', '0004_auto_20201106_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_age',
            field=models.IntegerField(default=25, verbose_name='年龄'),
        ),
    ]
